#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 (Shadowrocket 小火箭) | 快捷指令(推荐): 设置地理位置 https://www.icloud.com/shortcuts/a82717d8fdad4e6280866fcf911173f7 清理恢复位置 https://www.icloud.com/shortcuts/f42632d406504f24a2cd163af4fe012f | 选点页面: https://wloc-spoofer-secure.<你的子域名>.workers.dev/
#!author=Yu9191 Rewrite / CodeCraft39 Fork
#!homepage=https://github.com/CodeCraft39/wloc
#!icon=https://raw.githubusercontent.com/CodeCraft39/wloc/refs/heads/secure-worker/wloc.jpg
#!category=Tools

[Script]
Apple WLOC Request = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc(?:\?.*)?$,requires-body=1,binary-body-mode=1,max-size=1048576,timeout=15,script-path=https://raw.githubusercontent.com/CodeCraft39/wloc/refs/heads/secure-worker/dist/wloc.js,argument=mode=request&debug=true&failOpen=true
Apple WLOC Response = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc(?:\?.*)?$,requires-body=1,binary-body-mode=1,max-size=1048576,timeout=15,script-path=https://raw.githubusercontent.com/CodeCraft39/wloc/refs/heads/secure-worker/dist/wloc.js,argument=mode=response&debug=true&failOpen=true
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/CodeCraft39/wloc/refs/heads/secure-worker/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
